In [16]:
# Machine Learning Models
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

# Model Evaluation
from sklearn.metrics import (accuracy_score, precision_score, recall_score, roc_auc_score, f1_score, 
confusion_matrix, ConfusionMatrixDisplay, roc_curve, precision_recall_curve, auc, classification_report)

from sklearn.model_selection import cross_val_score, GridSearchCV
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
from sklearn.metrics import make_scorer
 
import random
random.seed(100)

import time
import pyodbc
print(pyodbc.drivers())
import numpy as np
import os
import time
import matplotlib.pyplot as plt
import seaborn as sns
 
# Data Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder

# mlflow
import mlflow
import mlflow.sklearn
from sqlalchemy import create_engine, text

['SQL Server', 'ODBC Driver 17 for SQL Server', 'SQL Server Native Client RDA 11.0', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [12]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.outliers_influence import variance_inflation_factor
import time
import pyodbc
from sklearn.utils import resample
print(pyodbc.drivers())
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score, roc_curve, precision_score, recall_score, f1_score, auc
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
from scipy import stats
import random
random.seed(42)

['SQL Server', 'ODBC Driver 17 for SQL Server', 'SQL Server Native Client RDA 11.0', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [3]:
df  = pd.read_pickle('../data/interim/processed_data.pkl')
df.shape

(121799, 35)

In [5]:
data = df.copy(deep=True)
data.head()

,Client_Income,Car_Owned,Bike_Owned,Active_Loan,House_Own,Child_Count,Credit_Amount,Loan_Annuity,Accompany_Client,Client_Income_Type,Client_Education,Client_Marital_Status,Client_Gender,Loan_Contract_Type,Client_Housing_Type,Population_Region_Relative,Age_Days,Employed_Days,Registration_Days,ID_Days,Mobile_Tag,Homephone_Tag,Workphone_Working,Client_Family_Members,Cleint_City_Rating,Application_Process_Day,Application_Process_Hour,Client_Permanent_Match_Tag,Client_Contact_Work_Tag,Score_Source_2,Score_Source_3,Phone_Change,Credit_Bureau,ID,Default
0,20250.0,1.0,0.0,1.0,1.0,0.0,15282.000000,1826.550049,Alone,Service,Graduation,M,Male,CL,Home,0.008575,14162.0,4129.00,7833.0,21.0,1,0,1,2.0,2.0,3.0,10,Yes,Yes,0.215068,0.511202,755.0,1.0,12138936,0
1,13500.0,0.0,0.0,1.0,1.0,0.0,60415.199219,3097.800049,Alone,Retired,Secondary,M,Male,CL,Home,0.009175,22493.0,12020.75,12617.0,5280.0,1,0,1,2.0,2.0,4.0,15,Yes,Yes,0.657508,0.549596,1687.0,4.0,12215264,0
2,12150.0,0.0,0.0,0.0,1.0,0.0,16320.150391,1294.650024,Alone,Retired,Secondary,W,Male,CL,Home,0.016612,20507.0,12020.75,2834.0,4053.0,1,0,0,1.0,2.0,3.0,9,Yes,Yes,0.063343,0.113294,533.0,5.0,12130547,0
3,15750.0,0.0,1.0,1.0,1.0,0.0,45000.000000,3007.350098,Alone,Service,Secondary,S,Female,CL,Home,0.008866,14536.0,3465.00,5871.0,2594.0,1,1,0,1.0,2.0,2.0,17,Yes,Yes,0.129861,0.590233,340.0,2.0,12106559,0
4,9000.0,0.0,0.0,0.0,0.0,0.0,22500.000000,2191.949951,Alone,Service,Secondary,S,Male,CL,Home,0.020892,15734.0,2504.00,6019.0,1191.0,1,0,0,1.0,2.0,2.0,11,Yes,Yes,0.418630,0.595456,2458.0,2.0,12186490,0

In [6]:
data['ID'] = data['ID'].astype('int')

In [7]:
imp_cols = ['Client_Income', 'Car_Owned', 'Active_Loan', 'House_Own',
        'Credit_Amount', 'Loan_Annuity', 
       'Client_Income_Type', 'Client_Education', 
       'Client_Gender', 'Loan_Contract_Type', 'Client_Housing_Type',
       'Age_Days', 'Employed_Days', 'ID_Days', 'Cleint_City_Rating',
       'Client_Permanent_Match_Tag', 
       'Score_Source_2', 'Score_Source_3', 'Phone_Change', 'Credit_Bureau',
       'ID', 'Default']

In [8]:
imp_data = data[imp_cols]
imp_data.shape

(121799, 22)

#### Mlflow

In [17]:
# Define Azure SQL Connection
server = 'loan-server-rpk.database.windows.net'
database = 'loanDB'
username = 'adminuser'
password = 'Rohit1234'
driver = 'ODBC+Driver+17+for+SQL+Server'

In [18]:
import mlflow
import mlflow.sklearn
from sqlalchemy import create_engine

try:
    # Set MLflow Tracking URI using SQL Server and Windows Authentication
    mlflow.set_tracking_uri(f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}")

 
    # Setting up the Name of experiment
    mlflow.set_experiment("Vehicle Loan Default Prediction")
except Exception as e:
    print(f"Connection failed: {e}")

2025/02/04 21:46:54 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/02/04 21:46:56 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 451aebb31d03, add metric step
INFO  [alembic.runtime.migration] Running upgrade 451aebb31d03 -> 90e64c465722, migrate user column to tags
INFO  [alembic.runtime.migration] Running upgrade 90e64c465722 -> 181f10493468, allow nulls for metric values
INFO  [alembic.runtime.migration] Running upgrade 181f10493468 -> df50e92ffc5e, Add Experiment Tags Table
INFO  [alembic.runtime.migration] Running upgrade df50e92ffc5e -> 7ac759974ad8, Update run tags with larger limit
INFO  [alembic.runtime.migration] Running upgrade 7ac759974ad8 -> 89d4b8295536, create latest metrics table
INFO  [89d4b8295536_create_latest_metrics_table_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 89d4b8295536 -> 2b4d017a5e9b, add model registry tables to db
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Adding registered_models and model_versions tables to database.
INFO  [2b4d017a5e9b_add_model_registry_tables_to_db_py] Migration complete!
INFO  [alembic.runtime.migration] Running upgrade 2b4d017a5e9b -> cfd24bdc0731, Update run status constraint with killed
INFO  [alembic.runtime.migration] Running upgrade cfd24bdc0731 -> 0a8213491aaa, drop_duplicate_killed_constraint
INFO  [alembic.runtime.migration] Running upgrade 0a8213491aaa -> 728d730b5ebd, add registered model tags table
INFO  [alembic.runtime.migration] Running upgrade 728d730b5ebd -> 27a6a02d2cf1, add model version tags table
INFO  [alembic.runtime.migration] Running upgrade 27a6a02d2cf1 -> 84291f40a231, add run_link to model_version
INFO  [alembic.runtime.migration] Running upgrade 84291f40a231 -> a8c4a736bde6, allow nulls for run_id
INFO  [alembic.runtime.migration] Running upgrade a8c4a736bde6 -> 39d1c3be5f05, add_is_nan_constraint_for_metrics_tables_if_necessary
INFO  [alembic.runtime.migration] Running upgrade 39d1c3be5f05 -> c48cb773bb87, reset_default_value_for_is_nan_in_metrics_table_for_mysql
INFO  [alembic.runtime.migration] Running upgrade c48cb773bb87 -> bd07f7e963c5, create index on run_uuid
INFO  [alembic.runtime.migration] Running upgrade bd07f7e963c5 -> 0c779009ac13, add deleted_time field to runs table
INFO  [alembic.runtime.migration] Running upgrade 0c779009ac13 -> cc1f77228345, change param value length to 500
INFO  [alembic.runtime.migration] Running upgrade cc1f77228345 -> 97727af70f4d, Add creation_time and last_update_time to experiments table
INFO  [alembic.runtime.migration] Running upgrade 97727af70f4d -> 3500859a5d39, Add Model Aliases table
INFO  [alembic.runtime.migration] Running upgrade 3500859a5d39 -> 7f2a7d5fae7d, add datasets inputs input_tags tables
INFO  [alembic.runtime.migration] Running upgrade 7f2a7d5fae7d -> 2d6e25af4d3e, increase max param val length from 500 to 8000
INFO  [alembic.runtime.migration] Running upgrade 2d6e25af4d3e -> acf3f17fdcc7, add storage location field to model versions
INFO  [alembic.runtime.migration] Running upgrade acf3f17fdcc7 -> 867495a8f9d4, add trace tables
INFO  [alembic.runtime.migration] Running upgrade 867495a8f9d4 -> 5b0e9adcef9c, add cascade deletion to trace tables foreign keys
INFO  [alembic.runtime.migration] Running upgrade 5b0e9adcef9c -> 4465047574b1, increase max dataset schema size
INFO  [alembic.runtime.migration] Running upgrade 4465047574b1 -> f5a4f2784254, increase run tag value limit to 8000
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
2025/02/04 21:47:07 INFO mlflow.tracking.fluent: Experiment with name 'Vehicle Loan Default Prediction' does not exist. Creating a new experiment.

In [19]:
## Let's check the onnection status

mlflow_tracking_uri = (f"mssql+pyodbc://{username}:{password}@{server}/{database}?driver={driver}")
 
# Setting up the MLflow Tracking URI
mlflow.set_tracking_uri(mlflow_tracking_uri)
 
try:
    # Creating SQLAlchemy engine
    engine = create_engine(mlflow_tracking_uri)
 
    # Testing the connection by running a query
    with engine.connect() as connection:
        # Using the text() function for SQL statement
        query = text("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES")
        result = connection.execute(query)
 
        # Fetching all the results 
        tables = result.fetchall()
 
        # list of tables
        print("Connection successful! Here are the tables in the database:")
        for table in tables:
            print(table[0])
 
    # if connection is successful
    mlflow.set_experiment("Vehicle Loan Default Prediction")
 
except Exception as e:
    print(f"Connection failed: {e}")

Connection successful! Here are the tables in the database:
alembic_version
experiment_tags
latest_metrics
registered_models
model_versions
registered_model_tags
model_version_tags
registered_model_aliases
datasets
inputs
input_tags
trace_info
trace_tags
trace_request_metadata
database_firewall_rules
customers_train
defaulters
customers_test
defaulters_test
waterTable
bronze_customers
silver_customers
gold_customers
gold_defaulters
silver_defaulters
bronze_defaulters
experiments
runs
tags
metrics
params

### Undersampling

In [20]:
# Step 1: Separate majority and minority classes
data_majority = imp_data[imp_data['Default'] == '0']
data_minority = imp_data[imp_data['Default'] == '1']

# Step 2: Define the percentage for undersampling (e.g., 40%)
undersample_percent = 0.4  # Retain 40% of majority class

# Calculate the number of records to keep from the majority class
n_majority_to_keep = int(len(data_majority) * undersample_percent)
print(n_majority_to_keep)

44783

In [21]:

# Step 3: Downsample the majority class
data_majority_downsampled = resample(
    data_majority,
    replace=False,  # Sample without replacement
    n_samples=n_majority_to_keep,  # Retain only the specified percentage
    random_state=42  # For reproducibility
)

# Step 4: Combine the downsampled majority class with the minority class
data_balanced = pd.concat([data_majority_downsampled, data_minority])

# Step 5: Shuffle the combined dataset
data_balanced = data_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# Step 6: Check the new class distribution
print("Class distribution after percentage-based undersampling:\n", data_balanced['Default'].value_counts())

Class distribution after percentage-based undersampling:
 Default
0    44783
1     9841
Name: count, dtype: int64

In [22]:
# Separate features and target
X = data_balanced.drop(columns=['Default'])
y = data_balanced['Default']

In [23]:
# Step 2: Encode categorical variables using One-Hot Encoding
X = pd.get_dummies(X, drop_first=True)  # Convert categorical features to numerical

# Step 3: Train-Test Split (80-20 ratio)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train shape: (43699, 30)
X_test shape: (10925, 30)
y_train: (43699,)
y_test: (10925,)

In [24]:
X_train.head()

,Client_Income,Car_Owned,Active_Loan,House_Own,Credit_Amount,Loan_Annuity,Age_Days,Employed_Days,ID_Days,Cleint_City_Rating,Score_Source_2,Score_Source_3,Phone_Change,Credit_Bureau,ID,Client_Income_Type_Govt Job,Client_Income_Type_Other,Client_Income_Type_Retired,Client_Income_Type_Service,Client_Education_Graduation dropout,Client_Education_Junior secondary,Client_Education_Secondary,Client_Gender_Male,Loan_Contract_Type_RL,Client_Housing_Type_Home,Client_Housing_Type_Municipal,Client_Housing_Type_Office,Client_Housing_Type_Rental,Client_Housing_Type_Shared,Client_Permanent_Match_Tag_Yes
31398,12150.0,0.0,0.0,0.0,39150.000000,2378.699951,9404.0,967.00,1988.0,2.0,0.342476,0.526295,501.0,0.0,12168513,False,False,False,True,False,False,True,False,False,True,False,False,False,False,True
45503,13500.0,1.0,1.0,1.0,22500.000000,1777.500000,11197.0,917.00,3743.0,2.0,0.513550,0.240541,1080.0,2.0,12217493,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True
33513,18000.0,1.0,1.0,1.0,107905.046875,3875.850098,15778.0,1330.00,2061.0,2.0,0.406130,0.694093,2962.0,0.0,12154826,False,False,False,False,False,False,False,True,False,True,False,False,False,False,True
33169,15750.0,1.0,0.0,1.0,78192.000000,4796.549805,16425.0,3343.00,5135.0,2.0,0.705521,0.713631,1682.0,2.0,12143392,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True
5577,9450.0,1.0,0.0,0.0,54504.000000,2067.750000,21933.0,12020.75,4064.0,2.0,0.387671,0.538863,1196.0,5.0,12100368,False,False,True,False,False,False,True,True,False,True,False,False,False,False,True

### Model Setup

In [28]:
# List of models to evaluate
models = {
    "Logistic Regression": LogisticRegression(class_weight='balanced', random_state=42),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Random Forest Classifier": RandomForestClassifier(random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss')
    }

In [29]:
# Hyperparameter grids for each model
param_grids = {
    "Logistic Regression": {
        'C': [0.01, 0.1, 1, 10, 100],
        'penalty': ['l1', 'l2'],
        'solver': ['liblinear', 'saga']
    },
    "Decision Tree Classifier": {
        'max_depth': [10, 20, None],
        'min_samples_split': [2, 5, 10],
        'min_samples_leaf': [1, 2, 4]
    },
    "Random Forest Classifier": {
        'n_estimators': [100, 300, 500],
        'max_depth': [5, 10, 20, 30, None],
        'min_samples_split': [2, 5, 10, 20],
        'min_samples_leaf': [1, 2, 4]
    },
    "XGBoost": {
        'n_estimators': [100, 200, 500],
        'max_depth': [3, 5, 7],
        'learning_rate': [0.01, 0.1, 0.2],
        'subsample': [0.6, 0.8, 1.0]
    }
}

In [30]:
def get_feature_importance(model, feature_names):
    """
    Extract feature importance or coefficients from the model.
    - Supports tree-based models (RandomForest, XGBoost) and linear models (LogisticRegression).
    """
    if hasattr(model, 'coef_'):  # For linear models
        importance = np.abs(model.coef_[0])  # Using absolute value of coefficients
    elif hasattr(model, 'feature_importances_'):  # For tree based models
        importance = model.feature_importances_
    else:
        return None  

    return pd.DataFrame({
        'Feature': feature_names,
        'Importance': importance
    }).sort_values(by='Importance', ascending=False)

In [31]:
feature_names = ['Client_Income', 'Car_Owned', 'Active_Loan', 'House_Own',
       'Credit_Amount', 'Loan_Annuity', 'Age_Days', 'Employed_Days', 'ID_Days',
       'Cleint_City_Rating', 'Score_Source_2', 'Score_Source_3',
       'Phone_Change', 'Credit_Bureau', 'Client_Income_Type_Govt Job',
       'Client_Income_Type_Other', 'Client_Income_Type_Retired',
       'Client_Income_Type_Service', 'Client_Education_Graduation dropout',
       'Client_Education_Junior secondary', 'Client_Education_Secondary',
       'Client_Gender_Male', 'Loan_Contract_Type_RL',
       'Client_Housing_Type_Home', 'Client_Housing_Type_Municipal',
       'Client_Housing_Type_Office', 'Client_Housing_Type_Rental',
       'Client_Housing_Type_Shared', 'Client_Permanent_Match_Tag_Yes']

In [32]:
def evaluate_models(models, param_grids, X_train, X_test, y_train, y_test, feature_names, experiment_name="Model Comparison", run_tags=None):
    """
    Evaluates models, logs comprehensive metrics in MLflow, and manages experiment metadata.
    
    Parameters:
    - models: Dictionary of models to evaluate.
    - param_grids: Dictionary of hyperparameters.
    - X_train, X_test, y_train, y_test: Datasets.
    - feature_names: List of feature names for importance extraction.
    - experiment_name: Name of the MLflow experiment.
    - run_tags: Optional tags for each run (dict).
    """
    mlflow.set_experiment(experiment_name)  
    results = []

    for model_name, model in models.items():
        print(f"Evaluating {model_name}...")

        start_time = time.time()

        grid_search = GridSearchCV(
            estimator=model, 
            param_grid=param_grids[model_name], 
            scoring='recall', 
            cv=3, 
            n_jobs=-1
        )
        grid_search.fit(X_train, y_train)

        best_model = grid_search.best_estimator_
        y_train_pred = best_model.predict(X_train)
        y_test_pred = best_model.predict(X_test)

        y_train_pred = y_train_pred.astype(int)
        y_test_pred = y_test_pred.astype(int)

        y_train = y_train.astype(int)
        y_test = y_test.astype(int)

        train_metrics = {
            'train_accuracy': accuracy_score(y_train, y_train_pred),
            'train_precision': precision_score(y_train, y_train_pred, average='weighted'),
            'train_recall': recall_score(y_train, y_train_pred, average='weighted'),
            'train_f1_score': f1_score(y_train, y_train_pred, average='weighted')
        }

        test_metrics = {
            'test_accuracy': accuracy_score(y_test, y_test_pred),
            'test_precision': precision_score(y_test, y_test_pred, average='weighted'),
            'test_recall': recall_score(y_test, y_test_pred, average='weighted'),
            'test_f1_score': f1_score(y_test, y_test_pred, average='weighted')
        }

        time_taken = time.time() - start_time
        feature_importance = get_feature_importance(best_model, feature_names)

        with mlflow.start_run(run_name=model_name) as run:
            # Log parameters and metrics
            mlflow.log_params(grid_search.best_params_)
            mlflow.log_metrics({**train_metrics, **test_metrics, 'time_taken': time_taken})

            # Log feature importance 
            if feature_importance is not None:
                feature_importance_file = f"../mlruns/{model_name}_feature_importance.csv"
                feature_importance.to_csv(feature_importance_file, index=False)
                mlflow.log_artifact(feature_importance_file)

            # Log tags for additional metadata
            if run_tags:
                mlflow.set_tags(run_tags)

            # Log the model itself
            mlflow.sklearn.log_model(best_model, model_name)

            # Register the model in MLflow Model Registry
            mlflow.register_model(f"../mlruns/runs:/{run.info.run_id}/{model_name}", model_name)

        results.append({
            'model': model_name,
            'best_params': grid_search.best_params_,
            'train_metrics': train_metrics,
            'test_metrics': test_metrics,
            'time_taken': time_taken
        })

        print(f"{model_name} completed in {time_taken:.2f} seconds with test recall: {test_metrics['test_recall']:.4f}")

    return results

In [33]:
results = evaluate_models(
    models, 
    param_grids, 
    X_train.drop(['ID'], axis=1), X_test.drop(['ID'], axis=1), y_train, y_test, 
    feature_names,
    experiment_name="Loan Defaulters Predction Model Comparison Experiment",
    run_tags={"author": "Rohit", "task": "Recall Optimization"}
)

2025/02/04 22:11:57 INFO mlflow.tracking.fluent: Experiment with name 'Loan Defaulters Predction Model Comparison Experiment' does not exist. Creating a new experiment.

Evaluating Logistic Regression...

2025/02/04 22:12:45 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2025/02/04 22:12:48 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2025/02/04 22:12:49 INFO mlflow.store.db.utils: Updating database tables
INFO  [alembic.runtime.migration] Context impl MSSQLImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Successfully registered model 'Logistic Regression'.
Created version '1' of model 'Logistic Regression'.

Logistic Regression completed in 29.08 seconds with test recall: 0.6793
Evaluating Decision Tree Classifier...

2025/02/04 22:13:22 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'Decision Tree Classifier'.
Created version '1' of model 'Decision Tree Classifier'.

Decision Tree Classifier completed in 16.67 seconds with test recall: 0.7559
Evaluating Random Forest Classifier...

2025/02/04 23:18:17 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'Random Forest Classifier'.
Created version '1' of model 'Random Forest Classifier'.

Random Forest Classifier completed in 3879.98 seconds with test recall: 0.8449
Evaluating XGBoost...

2025/02/04 23:19:24 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Successfully registered model 'XGBoost'.
Created version '1' of model 'XGBoost'.

XGBoost completed in 51.34 seconds with test recall: 0.8350